name: strain-design
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bottleneck=1.3.2
  - ca-certificates=2021.10.26
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numexpr=2.7.3
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.3
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.36.0
  - tk=8.6.11
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
      - ansi2html==1.8.0
      - anyio==3.4.0
      - appdirs==1.4.4
      - argon2-cffi==21.1.0
      - atomicwrites==1.4.0
      - attrs==21.2.0
      - auto-sklearn==0.15.0
      - babel==2.9.1
      - backcall==0.2.0
      - beartype==0.18.5
      - billiard==3.5.0.1
      - biopython==1.81
      - bleach==4.1.0
      - blessings==1.7
      - boolean-py==3.8
      - certifi==2019.9.11
      - cffi==1.15.0
      - charset-normalizer==2.0.7
      - click==8.0.3
      - cloudpickle==2.2.1
      - cobra==0.22.1
      - colorama==0.4.4
      - colour==0.1.5
      - commonmark==0.9.1
      - configspace==0.4.21
      - corda==0.4.2
      - cplex==22.1.1.2
      - cycler==0.11.0
      - cython==3.0.2
      - dash==2.13.0
      - dash-bio==1.0.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dask==2023.8.1
      - debugpy==1.5.1
      - decorator==5.1.0
      - defusedxml==0.7.1
      - depinfo==2.2.0
      - dill==0.3.4
      - diskcache==5.2.1
      - distributed==2023.8.1
      - distro==1.8.0
      - docloud==1.0.375
      - docplex==2.22.213
      - emcee==3.1.4
      - entrypoints==0.3
      - et-xmlfile==1.1.0
      - flask==2.2.5
      - fonttools==4.28.2
      - fsspec==2023.6.0
      - future==0.18.2
      - geoparse==2.0.3
      - gmcspy==1.0.1
      - gnomic==1.0.1
      - grako==3.18.1
      - greenlet==3.0.3
      - gurobipy==9.5.0
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - idna==3.3
      - importlib-metadata==6.8.0
      - importlib-resources==5.4.0
      - inspyred==1.0.1
      - iprogress==0.4
      - ipykernel==6.5.1
      - ipython==7.29.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.6.5
      - itsdangerous==2.1.2
      - jedi==0.18.1
      - jinja2==3.1.4
      - jmetalpy==1.5.5
      - joblib==1.3.0
      - jpype1==1.4.1
      - json5==0.9.6
      - jsonschema==3.2.0
      - jupyter-client==7.1.0
      - jupyter-core==4.9.1
      - jupyter-server==1.12.0
      - jupyterlab==3.2.4
      - jupyterlab-pygments==0.1.2
      - jupyterlab-server==2.8.2
      - jupyterlab-widgets==1.0.2
      - kaleido==0.2.1
      - kiwisolver==1.3.2
      - lazy-object-proxy==1.6.0
      - levenshtein==0.25.0
      - liac-arff==2.5.0
      - locket==1.0.0
      - markupsafe==2.1.5
      - matplotlib==3.5.0
      - matplotlib-inline==0.1.3
      - mewpy==0.1.22
      - mistune==0.8.4
      - more-itertools==7.2.0
      - mpmath==1.2.1
      - msgpack==1.0.5
      - multiprocess==0.70.12.2
      - nbclassic==0.3.4
      - nbclient==0.5.9
      - nbconvert==6.3.0
      - nbformat==5.1.3
      - nest-asyncio==1.5.1
      - networkx==3.2.1
      - notebook==6.4.6
      - numpy==1.21.4
      - openpyxl==3.0.9
      - optlang==1.8.1
      - ordered-set==4.0.2
      - packaging==21.3
      - palettable==3.3.0
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parmed==4.1.0
      - parso==0.8.2
      - partd==1.4.0
      - path==16.10.0
      - pathos==0.2.8
      - patsy==0.5.3
      - periodictable==1.6.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==8.4.0
      - pint==0.23
      - platformdirs==4.2.0
      - plotly==5.4.0
      - pluggy==0.13.1
      - pooch==1.8.1
      - pox==0.3.0
      - ppft==1.6.6.4
      - prometheus-client==0.12.0
      - prompt-toolkit==3.0.22
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - py==1.11.0
      - pyarrow==15.0.0
      - pycparser==2.21
      - pydantic==1.8.2
      - pyfastcore==0.0.2
      - pygments==2.10.0
      - pynisher==0.6.4
      - pyparsing==3.1.1
      - pyrfr==0.8.3
      - pyrsistent==0.18.0
      - pyswarms==1.3.0
      - pytest==4.6.11
      - python-libsbml==5.19.0
      - python-slugify==8.0.4
      - pyyaml==6.0.1
      - pyzmq==22.3.0
      - rapidfuzz==3.6.1
      - reframed==1.2.1
      - requests==2.26.0
      - retrying==1.3.4
      - rfc3986==1.5.0
      - rich==10.14.0
      - ruamel-yaml==0.17.17
      - ruamel-yaml-clib==0.2.6
      - scikit-learn==0.24.2
      - scipy==1.9.3
      - seaborn==0.11.2
      - send2trash==1.8.0
      - setuptools-scm==6.3.2
      - six==1.12.0
      - smac==1.2
      - sniffio==1.2.0
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.27
      - statsmodels==0.13.5
      - straindesign==1.9
      - swiglpk==5.0.10
      - sympy==1.12
      - tblib==2.0.0
      - tdqm==0.0.1
      - tenacity==8.0.1
      - terminado==0.12.1
      - testpath==0.5.0
      - text-unidecode==1.3
      - threadpoolctl==3.2.0
      - tomli==1.2.2
      - toolz==0.12.0
      - tornado==6.1
      - tqdm==4.64.1
      - traitlets==5.1.1
      - typing-extensions==4.8.0
      - tzdata==2024.1
      - uncertainties==3.1.7
      - urllib3==1.25.11
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==1.2.1
      - werkzeug==2.2.3
      - widgetsnbextension==3.5.2
      - zict==3.0.0
      - zipp==3.6.0
